# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Sejong Kim
description: >- # this means to ignore newlines until "baseurl:"
  This is Sejong Kim's personal page.
baseurl: "/bay" # the subpath of the site
url: "https://sejongk.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-sejongk.jpeg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: About
      slug: /
    - name: Projects
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: sejongk.dev@gmail.com
      link: mailto:sejongk.dev@gmail.com
   # - name: WeChat
   #   value: YourWeChatUsername
   #   link: "#"
  follow:
   # - name: Twitter
   #   link: http://twitter.com/YourTwitterUsername
   #   username: "@YourTwitterUsername"
   # - name: Facebook
   #   link: http://facebook.com/YourFacebookUsername
   # - name: LinkedIn
   #   link: http://linkedin.com/in/YourLinkedInUsername
    - name: GitHub
      link: http://github.com/sejongk
   # - name: Dribbble
   #   link: https://dribbble.com/YourDribbbleUsername
   # - name: RSS
   #   link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
